# Generated by Django 2.2.4 on 2019-08-10 01:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='create_At',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
